### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'runtime')

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#350] opened 2024-03-27 14:03 UTC
It's a bit hard to provide a decent repro right now, but the crash happens sometimes during startup (around 20% repro rate), with smoldot + rococo, and this is basically all the PAPI-related code in the application: 
```ts

const smoldotClinet = start();
const smProvider = getSmProvider(smoldotClinet);

const client: PolkadotClient = createClient(
  getChain({
    provider: smProvider(networkData.chainspec),
    keyring: [],
  }),
);

const api: TypedApi<typeof networkData.descriptors> = client.getTypedApi(networkData.descriptors);

//... these two calls happen at the same tick
    api.query.System.Account.getValue(this.address, { at: "finalized" }).then((value) => {
      //...
    });

    api.query.System.Account.watchValue(this.address, "finalized").forEach((value) => {
      //...
    });
//...
```
stacktrace:
```
/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71
    innerFrom(project(value, index++)).subscribe(
              ^
TypeError: Cannot read properties of undefined (reading 'runtime')
    at /Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/@polkadot-api/client/src/observableClient/chainHead/chainHead.ts:257:61
    at doInnerSub (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/operators/take.ts:60:26
    at OperatorSubscriber._this._next (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at ReplaySubject._subscribe (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/ReplaySubject.ts:80:18)
    at ReplaySubject.Observable._trySubscribe (/Users/cornholio/work/parity/polkadot-testnet-faucet/node_modules/rxjs/src/internal/Observable.ts:244:19)
```

**Comment by josepot** [comment] 2024-03-27 16:41
Thanks a lot for reporting this @mutantcornholio ! We are looking into it.

One thing that would really help us is if we had the logs of what happened, because that would allow us to reproduce exactly the bug that got triggered on your end. Once #351 gets merged, could you please use the `withLogsRecorder` that's exported from the `@polkadot-api/logs-provider` to capture the logs?

An example on how to use it would be: 

```ts
const client: PolkadotClient = createClient(
  getChain({
    provider: withLogsRecorder(
      smProvider(networkData.chainspec),
      (msg) => {
        // I mean, appending synchronously is less than ideal, but it's important that
        // the messages appear in the exact same order than they came. So, either this
        // of you can also use a `writeStream` and handle the `drain` event, or you can use
        // whichever logger library helps you do this.
        appendFileSync('./your-logs-file.logs', msg, {encoding: 'utf-8'})
      }
    ),
    keyring: [],
  }),
);
```

Thanks again!

**Comment by josepot** [comment] 2024-03-28 23:10
#354 fixes this. Thanks again for your collaboration!

**Closed** 2024-03-28 23:26 UTC
