### ISSUE TITLE
RpcError: Method not found on a Nodejs script

### ISSUE THREAD

**Issue by Tbaut** [polkadot-api/polkadot-api#656] opened 2024-08-23 13:59 UTC
Hello there, I'm running into an issue I can't explain for a super simple node script.
Please find the repo here: https://github.com/Tbaut/papi-node/blob/main/src/main.ts

To run it:
- `pnpm install`
- `pnpm dev`

I get the following error:
```
> papi-node@1.0.0 start /home/thib/Github/Tbaut/papi-node
> dotenv -e .env -- node ./dist/main.js

/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.1/node_modules/@polkadot-api/substrate-client/dist/index.js:505
        return error ? cb.onError(new RpcError(error)) : cb.onSuccess(result, (opaqueId, subscriber) => {
                                  ^

RpcError: Method not found
    at onMessage (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.1/node_modules/@polkadot-api/substrate-client/dist/index.js:505:35)
    at onMessageProxy (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.2.0/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/index.js:126:5)
    at _onMessageProxy (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.2.0/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/index.js:164:20)
    at WS._onMessage (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/@polkadot-api+ws-provider@0.2.0/node_modules/@polkadot-api/ws-provider/dist/node/node.js:25:39)
    at callListener (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:290:14)
    at WS.onMessage (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/event-target.js:209:9)
    at WS.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/home/thib/Github/Tbaut/papi-node/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/receiver.js:596:14) {
  code: -32601,
  data: undefined
}

Node.js v21.7.1

```

**Comment by josepot** [comment] 2024-08-23 14:52
I'm closing this issue, because I checked and I can confirm that this is what's happening. Feel free to open it again, if I'm mistaken, of course.

**Closed by josepot** 2024-08-23 14:52 UTC
