### ISSUE TITLE
Uknown operationId

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#636] opened 2024-08-15 21:04 UTC
Instructions:

Run `pnpm test`. As soon as u see "broadcasted", CTRL+C and then run `pnpm test` again. The tx u submit now should have a stale issue. Then just let it run, keep retrying until you see something like:

```
Uknown operationId on {
  event: 'operationCallDone',
  operationId: '21',
  output: '0x00db0100000000000000049014495d6197bf209b8e3403ae52ca793d17aede3992af1157c286ebb96b853c243a000000370000000000000001'
}
```

Repro: https://github.com/ryanleecode/papi-test-2
Logs: https://gist.github.com/ryanleecode/b100bdae429b64571c736e4e8b0e18bf

related: https://github.com/polkadot-api/polkadot-api/issues/634

**Comment by josepot** [comment] 2024-08-16 03:05
> The tx u submit now should have a stale issue

No, it shouldn't. Because by default, before broadcasting the transaction, the transaction is validated against the currently finalized block, so against that block the transaction is valid.

You do realize that you are purposely creating a race-condition in which just one of the 2 transactions will be included, right? Also, you do realize that 99.9% of the time that would be the first transaction?

Are we on the same page thus far?

**Comment by ryanleecode** [comment] 2024-08-16 03:43
this is just steps to repro not actually how its being used.

we have an web server that submits usernames but it associated with one account. did some testing with mutliple concurrent requests and saw this log warning showed up. discussed with @voliva to just open an issue so u guys can take a look at it...

anyways im already aware this approach isnt viable. were going to run a cron job that runs a batch call instead

**Comment by josepot** [comment] 2024-08-16 04:29
In the logs I can clearly see that everything is working as expected. I'm afraid that is not a bug, but rather a misunderstanding and/or a misusage of the library.

The "Uknown operationId on" message is to be expected. What's happening is that there is an ongoing operation got canceled, but we received its started event anyways. The log is there because in other cases that could be something problematic, but not in this case. In the logs we can clearly see that's the case, because these 2 things happened at the exact same time:

```
1-2024-08-15T21:02:06.544Z-<<-{"jsonrpc":"2.0","result":{"result":"started","operationId":"21"},"id":"1-32"}
1-2024-08-15T21:02:06.544Z->>-{"jsonrpc":"2.0","id":"1-34","method":"chainHead_v1_stopOperation","params":["fRO6LmRycl4DEYL8","21"]}
```

So, IMO everything is fine here.

I'm closing this issue. However, if there is anything that you think I missed, please feel free to open it again.

**Closed by josepot** 2024-08-16 04:29 UTC
