### ISSUE TITLE
Darwinia parachain error - Execution aborted due to trap

### ISSUE THREAD

**Issue by michaeldev5** [polkadot-api/polkadot-api#813] opened 2024-10-22 16:38 UTC
Hello @josepot,

I am opening a separate issue as we discussed. I made a minimal reproduction repository for Darwinia parachain using Paseo RPC endpoint. I am using latest Polkadot-API v1.6.2. The identical error also happens on Mythos, Crab but I didn't find Paseo endpoint for these nodes.

Minimal reproduction repository: https://github.com/michaeldev5/bug-reproduction

In the minimal reproduction code I am trying to create an XTokens transfer and sign it using EVM signer but I receive the following error:

```
file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/chainhead/operation-promise.mjs:36
            rej(new OperationError(_e.error));
                ^

OperationError: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x58eeb2 - <unknown>!rust_begin_unwind
    1: 0x1a606 - <unknown>!core::panicking::panic_fmt::h916104d5f54b6e68
    2: 0x52303d - <unknown>!AccountNonceApi_account_nonce
    at Object.next (file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/chainhead/operation-promise.mjs:36:17)
    at Object.next (file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/internal-utils/subscriptions-manager.mjs:12:30)
    at Object.onAllFollowEventsNext [as next] (file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/chainhead/chainhead.mjs:28:30)
    at Object.next (file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/internal-utils/subscriptions-manager.mjs:12:30)
    at onMessage (file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/client/createClient.mjs:46:23)
    at file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+polkadot-sdk-compat@2.3.1/node_modules/@polkadot-api/polkadot-sdk-compat/dist/esm/parsed.mjs:22:13
    at file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+polkadot-sdk-compat@2.3.1/node_modules/@polkadot-api/polkadot-sdk-compat/dist/esm/parsed-enhancers/fix-descendant-values.mjs:46:5
    at file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+polkadot-sdk-compat@2.3.1/node_modules/@polkadot-api/polkadot-sdk-compat/dist/esm/utils.mjs:33:26
    at file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+polkadot-sdk-compat@2.3.1/node_modules/@polkadot-api/polkadot-sdk-compat/dist/esm/parsed-enhancers/fix-unordered-blocks.mjs:59:7
    at file:///Users/michael/Projects/tools/node_modules/.pnpm/@polkadot-api+polkadot-sdk-compat@2.3.1/node_modules/@polkadot-api/polkadot-sdk-compat/dist/esm/parsed-enhancers/fix-premature-blocks.mjs:55:7

Node.js v20.17.0
```

Hope this helps and thank you for your assistance!

With kind regards,
Team ParaSpell ✨

**Comment by josepot** [comment] 2024-10-22 18:38
Thank you so much for reporting this issue. We will get to it ASAP. In the meanwhile, I just wanted to thank you for all the details provided in this issue, specially for setting up a repro. This is going to help us a great deal to identify the problem. So, thanks for taking the time and the effort that you put into this.

**Comment by michaeldev5** [comment] 2024-10-22 20:33
You're welcome. Glad to help and make it easier for you! 🙏

**Comment by josepot** [comment] 2024-10-23 07:17
Ok, I have been looking into this and it is indeed related with #807. Basically, what happened is that we didn't realize that these "ETH like" chains expected a different format for the extrinsic. We have to make fixes into the 3 signers that we have. I just finished fixing the `@polkadot-api/signer` package ([first PAPI TX](https://mythos.subscan.io/extrinsic/0x7e28651ffda4f8bccae7e1877b3a91881623aeb7bd5e6eaab31934ed5b3dc6df) on a "ETH-like" parachain), and now I have to fix the PJS signer and the ledger-signer. We will also have to fix the `getEstimatedFees` API, but that should be easier.

I hope to have the PR ready before EOD today.

**Comment by josepot** [comment] 2024-10-24 13:03
This issue should have been fixed with #807. However, please read [this](https://github.com/polkadot-api/polkadot-api/discussions/819). 🙏

**Closed by josepot** 2024-10-24 13:03 UTC

**Comment by michaeldev5** [comment] 2024-10-27 19:24
Thank you so much for fixing this issue so quickly. 🎉

I have used the example code you provided and its working in my tests now!

However, regarding the browser the `polkadot-api/pjs-signer` function `getAccounts()` is not finding my Talisman EVM account. Is it not supported yet or do I need to use a different library to connect to EVM accounts in browser extensions?

Thank you for helping!

With kind regards,
Team ParaSpell ✨

**Comment by josepot** [comment] 2024-10-28 06:22
> However, regarding the browser the `polkadot-api/pjs-signer` function `getAccounts()` is not finding my Talisman EVM account. Is it not supported yet or do I need to use a different library to connect to EVM accounts in browser extensions?

It should work. Also, I'm pretty sure that I tried it also with Talisman and it did work. In particular [this change](https://github.com/polkadot-api/polkadot-api/pull/817/files#diff-9aa60ba7b25709cede28d04d57c749c8fae23974e3abfebd22432267dbf3c8caR20) is the one that should make the account available. 🤔

I'm going to look into this right away, though. In the meanwhile, please double-check that you are actually using the latest version (if you are using vite, please remove the cache `rm -rf ./node_modules/.vite`) and if the problem persists, please open a new issue. 🙏

**Comment by josepot** [comment] 2024-10-28 09:21
I did double-check on a fresh new project that also uses Talisman and everything seems to be working fine. Did you perhaps forget to connect the account to the DApp? 🤔 If that's not the case, then please open a new issue and explain how to reproduce it 🙏

**Comment by michaeldev5** [comment] 2024-10-28 12:07
@josepot It was indeed my fault. Everything works perfectly after deleting all node modules in the project and reinstalling dependencies. I apologize 🙏. Thank you for your quick support!

**Comment by josepot** [comment] 2024-10-28 12:16
> @josepot It was indeed my fault. Everything works perfectly after deleting all node modules in the project and reinstalling dependencies. I apologize 🙏. Thank you for your quick support!

my pleasure! no worries at all! thank you for letting us know that things work correctly now!
